version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "9090:9090"
    environment:
      - NODE_ENV=development
      - DUCKDB_POOL_SIZE=5
  client:
    build: ./client
    ports:
      - "80:8080"
