name: Deploy API Service

on: 
  push: 
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'
  workflow_dispatch:

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: "github.ref == 'refs/heads/main'"
    steps:
      - name: "Check if secrets exists"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST_DNS }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: ${{ secrets.DEPLOY_TARGET_DIR }}
        if: >
          ${{ env.DEPLOY_SSH_KEY != null }} &&
          ${{ env.DEPLOY_HOST_DNS != null }} &&
          ${{ env.DEPLOY_USERNAME != null }} &&
          ${{ env.DEPLOY_TARGET_DIR != null }}
        run: '"The one or more secrets has not been made, please go to \"settings > secrets > actions\" to create it"'
      - uses: actions/checkout@v3
      - run: rm -rf .git
      - uses: easingthemes/ssh-deploy@main
        env:
          ARGS: -rlgoDzvc -i --delete
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST_DNS }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          SCRIPT_BEFORE: sudo supervisorctl stop substrait-fiddle:*
          SCRIPT_AFTER: sudo chown -R www-data:www-data ${{ secrets.DEPLOY_TARGET_DIR }} && sudo supervisorctl start substrait-fiddle:*
          TARGET: ${{ secrets.DEPLOY_TARGET_DIR }}
