name: Deploy api + docker

on: 
  push: 
    branches: [ DVO-4886-use-docker-compose ]
  workflow_dispatch:

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run updates
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.BASE_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: |
          sudo apt update
          sudo apt upgrade -y
  
    - name: Install Docker and Docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.BASE_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: |
          sudo apt install docker -y
          sudo apt install docker.io -y
          sudo apt install docker-compose -y
    
    # - name: Install npm
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DEPLOY_HOST_DNS }}
    #     username: ${{ secrets.BASE_USER }}
    #     key: ${{ secrets.DEPLOY_SSH_KEY }}
    #     port: 22
    #     script: |
    #       sudo apt install npm -y

    - name: Configure deploy user
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST_DNS }}
        username: ${{ secrets.BASE_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: |
          sudo useradd -m -b /var/lib -G docker ${{ env.SSH_USER }}
          export SSH_USER=${{ secrets.DEPLOY_USERNAME }}
          export PUB_KEY=${{ secrets.DEPLOY_PUBLIC_KEY }}
          echo ${{ env.SSH_USER }}
          echo ${{ env.PUB_KEY }}
          sudo chown ${{ env.SSH_USER }}:${{ env.SSH_USER }} /var/lib/${{ env.SSH_USER }}/.ssh && sudo chmod 0500 /var/lib/${{ env.SSH_USER }}/.ssh
          echo ${{ env.PUB_KEY }} > deploy_key.pub
          sudo install -o ${{ env.SSH_USER }} -g ${{ env.SSH_USER }} -m 0600 deploy_key.pub /var/lib/${{ env.SSH_USER }}/.ssh/authorized_keys
          sudo chmod 0500 /var/lib/${{ env.SSH_USER }}/.ssh
          rm deploy_key.pub
      env:
        SSH_USER: ${{ secrets.DEPLOY_USERNAME }}
        PUB_KEY: ${{ secrets.DEPLOY_PUBLIC_KEY }}

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.DEPLOY_HOST_DNS }}
        ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        docker_compose_prefix: testing
