name: Deploy api + docker

on: 
  push: 
    branches: [ DVO-4886-use-docker-compose ]
  workflow_dispatch:

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rm -rf .git
    # - name: Install dependencies
    #   run: make install-dep
    - uses: astappiev/docker-compose-remote-action@master
      name: Docker-Compose Remote Deployment
      with:
          ARGS: -rlgoDzvc -i --delete
          # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          # REMOTE_HOST: ${{ secrets.DEPLOY_HOST_DNS }}
          # REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          ssh_host: ${{ secrets.DEPLOY_HOST_DNS }}
          ssh_user: ubuntu
          ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          docker_compose_prefix: substrait-fiddle
          ssh_host_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
