name: Deploy api + docker

on: 
  push: 
    branches: [ DVO-4886-use-docker-compose ]
  workflow_dispatch:

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5
  REMOTE_USER: ${{ secrets.BASE_USER }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update and upgrade packages
      run: sudo apt update && sudo apt upgrade -y
    - name: Install Docker
      run: sudo apt install docker -y
    # - name: Install Docker.io
    #   run: sudo apt install docker.io -y
    - name: Install Docker-Compose
      run: sudo apt install docker-compose -y
    # - name: Stop and Start Docker service
    #   run: systemctl stop docker && systemctl start docker
    - name: Install NPM
      run: sudo apt install npm -y
    - name: Create deployment user
      run: sudo useradd -m -b /var/lib -G docker docker-deploy
    - name: Configure deployment directory
      run: sudo mkdir /var/lib/docker-deploy/.ssh
    - name: Change ownership and permissions
      run: sudo chown docker-deploy:docker-deploy /var/lib/docker-deploy/.ssh && chmod 0500 /var/lib/docker-deploy/.ssh
    - name: Add SSH key
      run: |
        sudo echo ${{ secrets.DEPLOY_PUBLIC_KEY }} > /var/lib/docker-deploy/.ssh/authorized_keys
        sudo cat deploy_key.pub >> /var/lib/docker-deploy/.ssh/authorized_keys
        sudo install -o docker-deploy -g docker-deploy -m 0600 deploy_key.pub /var/lib/docker-deploy/.ssh/authorized_keys
    
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.DEPLOY_HOST_DNS }}
        ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        docker_compose_prefix: testing

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - run: rm -rf .git
#     # - name: Install dependencies
#     #   run: make install-dep
#     - name: Build Docker image
#       run: docker-compose up
#       env:
#         ARGS: -rlgoDzvc -i --delete
#         SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
#         REMOTE_HOST: ${{ secrets.DEPLOY_HOST_DNS }}
#         REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
#         SCRIPT_AFTER: sudo chown -R www-data:www-data ${{ secrets.DEPLOY_TARGET_DIR }} && sudo supervisorctl start substrait-fiddle:*
#         TARGET: ${{ secrets.DEPLOY_TARGET_DIR }}
          # ssh_host: ${{ secrets.DEPLOY_HOST_DNS }}
          # ssh_user: ${{ secrets.DEPLOY_USERNAME }}
          # ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          # docker_compose_prefix: substrait-fiddle
          # ssh_host_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
          # ssh_jump_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
