name: Deploy api + docker

on: 
  push: 
    branches: [ DVO-4886-use-docker-compose ]
  workflow_dispatch:

env:
  VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
  DUCKDB_POOL_SIZE: 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rm -rf .git
    # - name: Install dependencies
    #   run: make install-dep
    - uses: astappiev/docker-compose-remote-action@master
      name: Docker-Compose Remote Deployment
      with:
          ARGS: -rlgoDzvc -i --delete
          # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          # REMOTE_HOST: ${{ secrets.DEPLOY_HOST_DNS }}
          # REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          SCRIPT_AFTER: sudo chown -R www-data:www-data ${{ secrets.DEPLOY_TARGET_DIR }} && sudo supervisorctl start substrait-fiddle:*
          TARGET: ${{ secrets.DEPLOY_TARGET_DIR }}
          ssh_host: ${{ secrets.DEPLOY_HOST_DNS }}
          ssh_user: ubuntu
          ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          docker_compose_prefix: substrait-fiddle
          ssh_jump_public_key: ~/.ssh/known_hosts
          ssh_host_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAf/5qMOSmVrqaA3wuEB9o+NRXzEwSOrYwXMPklMSyG6pvzvM3vfc7bUasuDEX0Pdooa0JiG2VSCtoYeLEXqx1mxxI6q59sEFBYQI8q3k+RO1UR3NN4ByCs7+70XrbfubjKtpZY38PUrOhneh7uNUzm0VdXqR5BnjcO/douDxsfJ0SpBULEUHwNQxawFqUyWPuXFIZTPytDZGgRpLhUYdxXCrKtODsbvl7cbssB+70cUEs0yb0LG5H1Shvfr6OIq4ZEYGgHgtPJo7fQhXxebw4ChKtMvouQ58422myHmQKUvvI+SmiJMpQyLRAcsoJKdpwnp0wxHJzx0Dn8Rwp+ggX substrait-fiddle-production-key-pair
